extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/*/*.bril'
timeout = 20

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "target/debug/rust_stuff --mode pipe - lvn",
    "bril2json",
    "brili -p {args}",
]
