extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brilirs -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "target/debug/rust_stuff --mode pipe dce",
    "brilirs -p {args}",
]

